### ISSUE TITLE
Tooltip behavior

### ISSUE THREAD

**Issue by benoitjchevalier** [predixdesignsystem/px-vis-boxplot#42]
Tooltip flickers when hovering and moving the mouse over the box of a box and whiser. It gets a `mouseout` event from the median line apparently.

Also we need to make sure that the opacity change and the tooltip showing/hiding are always in sync. They be desynced now, but probably because of the issue described above. A safer approach might be to tie opacity change to tooltip actual show/hide events.

**Comment by nonmetalhail** [comment]
SVG elements interrupt mousevents from lower elements. So both the median and the mean dot will need their own mouseevents. You could also try setting their pointer-events to none and see if that fixes it.

**Comment by nonmetalhail** [comment]
This should be a P1
