### ISSUE TITLE
Create a glitch for boxplot

### ISSUE THREAD

**Issue by benoitjchevalier** [predixdesignsystem/px-vis-boxplot#43]

**Comment by drewharvey** [comment]
I think we agreed to do this, but I will need help with the details.

**Comment by drewharvey** [comment]
Working glitch: https://glitch.com/edit/#!/px-vis-boxplot-demo

**Comment by nonmetalhail** [comment]
One is created, but ownership needs to be transfered

**Comment by drewharvey** [comment]
@nonmetalhail How and who do I transfer ownership of glitch to?

**Comment by benoitjchevalier** [comment]
can we remix it maybe?

**Comment by nonmetalhail** [comment]
Oh, duh. I'll just remix it
