### ISSUE TITLE
(P2) Threshold lines being rendered outside of the Axes

### ISSUE THREAD

**Issue by Aileen-H** [predixdesignsystem/px-vis-boxplot#48]
The threshold lines which are outside of the axis should not be displayed (need to add a clippath like other charts, same for outliers outside of axis)
![screen shot 2018-02-05 at 5 50 28 pm](https://user-images.githubusercontent.com/21231643/35881037-5bd0f5b4-0b34-11e8-8a17-13f7120440da.png)

**Comment by nonmetalhail** [comment]
I think it has been mentioned before, but you should be using the `clipPath` component and pass the clip paths to drawing components. That will address this issue.
