### ISSUE TITLE
Mean diameter size

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-boxplot#50]
**Current state of the mean (circle):**
<img width="78" alt="screen shot 2018-02-08 at 10 49 56 am" src="https://user-images.githubusercontent.com/30873778/35992047-fbe993c8-0cbd-11e8-82eb-1fc309ed13da.png">

**Expected state of the mean, 5px diameter:**
<img width="448" alt="screen shot 2018-02-08 at 10 51 39 am" src="https://user-images.githubusercontent.com/30873778/35992092-24227e18-0cbe-11e8-8061-f4e2be592a9c.png">

**Comment by alump** [comment]
I assume this should have css variable also.
