### ISSUE TITLE
Median line thickness

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-boxplot#51]
Current state of median line:
<img width="78" alt="screen shot 2018-02-08 at 10 49 56 am" src="https://user-images.githubusercontent.com/30873778/35992337-df430442-0cbe-11e8-91ab-022b3a61c5b5.png">

Expected state of median line, 2px thickness
<img width="448" alt="screen shot 2018-02-08 at 10 51 39 am" src="https://user-images.githubusercontent.com/30873778/35992335-da04c844-0cbe-11e8-8f63-5f263bf0d171.png">

**Comment by alump** [comment]
I assume this also should be from css variable?

**Comment by Aileen-H** [comment]
Priority 3
