### ISSUE TITLE
Tooltip styling

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-boxplot#52]
**Tooltip current state:**
<img width="186" alt="screen shot 2018-02-08 at 11 00 21 am" src="https://user-images.githubusercontent.com/30873778/35992508-4ba9393a-0cbf-11e8-9e6c-a6a7482edbab.png">

**Tooltip expected state:**
<img width="921" alt="screen shot 2018-02-08 at 11 01 53 am" src="https://user-images.githubusercontent.com/30873778/35992583-84026482-0cbf-11e8-9728-0545782817f3.png">

**Comment by Aileen-H** [comment]
Priority 3

**Comment by drewharvey** [comment]
px-tooltip does not have a way to set padding values.  We can still set the font size and colors.

**Comment by Aileen-H** [comment]
Issue #67 relates to this issue

**Comment by drewharvey** [comment]
This is partially related to #67.  GE is to investigate making tooltips capable of styling, but until then PR #83 has updated the default style to look as the spec required.

**Comment by nonmetalhail** [comment]
Closing this; see #67
