### ISSUE TITLE
Change the way box-whisker checks for colors

### ISSUE THREAD

**Issue by nonmetalhail** [predixdesignsystem/px-vis-boxplot#64]
Include the `PxVisBehavior.updateStylesOverride` behavior and set an observer to trigger on `_stylesUpdated`. Then you can kill this code: [https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-box-whisker.html#L265-L270](https://github.com/vaadin/px-vis-boxplot/blob/master/px-vis-box-whisker.html#L265-L270)

**Comment by Aileen-H** [comment]
Priority 2
